# Source files

file(GLOB_RECURSE LIB_SOURCE_FILES "${PROJECT_SOURCE_DIR}/${SOURCE_DIR}/*pp")
file(GLOB_RECURSE LIB_HEADER_FILES "${PROJECT_SOURCE_DIR}/${INCLUDE_DIR}/*.h*")
file(GLOB_RECURSE TEST_SOURCE_FILES "${PROJECT_SOURCE_DIR}/${TEST_DIR}/*pp")

foreach(F ${LIB_HEADER_FILES})
  # Filter out non exposed header files
  if(NOT F MATCHES ".*/${IMPLEMENTATION_DIR}/*")
    list(APPEND LIB_EXPOSED_HEADER_FILES ${F})
  endif()
endforeach()

foreach(F ${LIB_HEADER_FILES})
  get_filename_component(FILE_DIR ${F} DIRECTORY)
  if(FILE_DIR MATCHES ".*/${IMPLEMENTATION_DIR}")
    list(APPEND LIB_REQUIRED_DIRS ${FILE_DIR})
  endif()
endforeach()

list(REMOVE_DUPLICATES LIB_REQUIRED_DIRS)
