# Source files

file(GLOB_RECURSE LIB_SOURCE_FILES "${PROJECT_SOURCE_DIR}/${SOURCE_DIR}/*pp")
file(GLOB_RECURSE LIB_HEADER_FILES "${PROJECT_SOURCE_DIR}/${INCLUDE_DIR}/*pp")
file(GLOB_RECURSE TEST_SOURCE_FILES "${PROJECT_SOURCE_DIR}/${TEST_DIR}/*pp")
set(MAIN_TEST_SOURCE_FILE ${PROJECT_SOURCE_DIR}/${TEST_DIR}/main.cpp)

foreach(F ${LIB_HEADER_FILES})
  # Filter out non exposed header files
  if(NOT F MATCHES ".*/${IMPLEMENTATION_DIR}/*")
    list(APPEND LIB_EXPOSED_HEADER_FILES ${F})
  endif()
endforeach()

list(APPEND TEST_SOURCE_FILES ${MAIN_TEST_SOURCE_FILE})
